import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#434655",
        primary: "#004ac6",
        "on-tertiary-container": "#ffece5",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#783200",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-surface": "#2d3133",
        "surface-tint": "#0053db",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "tertiary-fixed": "#ffdbca",
        secondary: "#006c49",
        "on-surface": "#191c1e",
        background: "#f7f9fb",
        tertiary: "#8e3c00",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        surface: "#f7f9fb",
        "primary-fixed-dim": "#b4c5ff",
        "outline-variant": "#c3c6d7",
        "on-primary-fixed": "#00174b",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "primary-container": "#2563eb",
        "secondary-container": "#6cf8bb",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#341100",
        "on-primary-container": "#eeefff",
        "tertiary-fixed-dim": "#ffb690",
        "tertiary-container": "#b54e00",
        "on-secondary-container": "#00714d",
        outline: "#737686",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        "inverse-primary": "#b4c5ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#005236",
        "on-primary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#002113",
        "primary-fixed": "#dbe1ff",
        "surface-dim": "#d8dadc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "section-gap": "64px",
        "margin-desktop": "40px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        gutter: "24px",
        "container-max": "1200px",
        "stack-md": "16px",
        "margin-mobile": "16px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "data-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "data-md": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
